version: "3"

services:
  dj_helper:
    container_name: dj-helper
    restart: always
    build: .
    volumes:
      - "./src:/app"
      - "./notebooks:/notebooks"
      - "${SOULSEEK_DIR}:/soulseek"
      - "${MUSIC_STORE_DIR}:/music_store"
      - "${BANDCAMP_DIR}:/bandcamp"
    command: sh -c 'python main.py'
